version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: caller information Build and push Docker image
          command: |
            sudo docker build -t cloudplexng/callerinfo:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push cloudplexng/callerinfo:${CIRCLE_BUILD_NUM}